[tool.poetry]
name = "letmebot"
version = "0.1.0"
description = ""
authors = ["Joscha Götzer <joscha.goetzer@teamviewer.com>"]

[tool.poetry.dependencies]
python = "^3.8"
aiogram = "^2.11.2"
loguru = "^0.5.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
